#!/usr/bin/env python3
"""
compare_with_openblas.py — Performance comparison: Week 2 SGEMM vs OpenBLAS

Compares SGEMM implementations on various matrix sizes and thread counts.
Uses the generic benchmark_runner to get highly accurate C-level timings.

Usage:
    python3 autotuning/compare_with_openblas.py                    # Default matrices
    python3 autotuning/compare_with_openblas.py --sizes 256 512 1024  # Custom sizes
    python3 autotuning/compare_with_openblas.py -t 1 2 4 8         # Thread scaling
    python3 autotuning/compare_with_openblas.py --output results/report.md  # Save markdown
"""

import sys
import os
import argparse
from pathlib import Path

# Add parent directory to path to import benchmark_runner
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from benchmark_runner import BenchmarkRunner, SGEMMConfig

WEEK2_BIN = os.path.join(os.path.dirname(os.path.dirname(__file__)), "bin", "bench_sgemm")
OPENBLAS_BIN = os.path.join(os.path.dirname(os.path.dirname(__file__)), "bin", "compare_direct_openblas")

def main():
    parser = argparse.ArgumentParser(description="Compare Week 2 SGEMM with OpenBLAS performance")
    parser.add_argument('--sizes', type=int, nargs='+', default=[256, 512, 1024], help='Matrix sizes to test')
    parser.add_argument('-t', '--threads', type=int, nargs='+', default=[1, 8, 16], help='Thread counts to test')
    parser.add_argument('--kernel', default='6x16', help='Week 2 kernel type')
    parser.add_argument('-o', '--output', default="results/comparison_report.md", help='Save results to Markdown file')
    args = parser.parse_args()
    
    print("=" * 70)
    print("SGEMM Performance Comparison: Week 2 vs OpenBLAS")
    print("=" * 70)
    print(f"Matrix sizes: {args.sizes}")
    print(f"Thread counts: {args.threads}")
    print(f"Week 2 kernel: {args.kernel}\n")
    
    runner_w2 = BenchmarkRunner(bench_bin=WEEK2_BIN, verbose=False)
    runner_ob = BenchmarkRunner(bench_bin=OPENBLAS_BIN, verbose=False)
    
    results = []
    
    for size in args.sizes:
        for threads in args.threads:
            print(f"--- {size}x{size}x{size}, {threads} thread{'s' if threads!=1 else ''} ---")
            
            cfg = SGEMMConfig(M=size, N=size, K=size, threads=threads, kernel=args.kernel)
            
            print("  Running OpenBLAS... ", end="", flush=True)
            ob_res = runner_ob.run(cfg, use_cache=False)
            if ob_res.success:
                print(f"{ob_res.median_gflops:.1f} GFLOP/s")
            else:
                print(f"FAILED ({ob_res.error})")
                
            print("  Running Week 2...   ", end="", flush=True)
            w2_res = runner_w2.run(cfg, use_cache=False)
            if w2_res.success:
                print(f"{w2_res.median_gflops:.1f} GFLOP/s")
            else:
                print(f"FAILED ({w2_res.error})")
                
            if ob_res.success and w2_res.success:
                ratio = w2_res.median_gflops / ob_res.median_gflops if ob_res.median_gflops > 0 else 0
                marker = "✓" if ratio >= 0.9 else "X"
                print(f"  {marker} Week 2 is {ratio*100:.1f}% of OpenBLAS\n")
                results.append({
                    'size': size, 'threads': threads, 'ob': ob_res.median_gflops,
                    'w2': w2_res.median_gflops, 'ratio': ratio
                })
                
    # Print summary
    print("=" * 70)
    print("SUMMARY TABLE")
    print("=" * 70)
    print(f"{'Size':10} {'Threads':8} {'OpenBLAS':>12} {'Week 2':>12} {'Ratio':>10}")
    print("-" * 70)
    for r in results:
        print(f"{str(r['size'])+'x'+str(r['size']):10} {r['threads']:8} {r['ob']:12.1f} {r['w2']:12.1f} {r['ratio']:10.1%}")

    # Generate Markdown Report
    if args.output:
        os.makedirs(os.path.dirname(args.output), exist_ok=True)
        with open(args.output, "w") as f:
            f.write("# SGEMM Performance Report: Week 2 vs OpenBLAS\n\n")
            f.write("## Overview\n")
            f.write(f"Target Kernel: `{args.kernel}`\n\n")
            f.write("| Matrix Size | Threads | OpenBLAS (GFLOP/s) | Week 2 (GFLOP/s) | Ratio (Week2/OB) | Status |\n")
            f.write("|---|---|---|---|---|---|\n")
            for r in results:
                status = "🟢 Pass" if r['ratio'] >= 0.9 else "🔴 Fail"
                f.write(f"| {r['size']}x{r['size']} | {r['threads']} | {r['ob']:.1f} | {r['w2']:.1f} | **{r['ratio']:.1%}** | {status} |\n")
            f.write("\n_Generated by autotuning/compare_with_openblas.py_\n")
        print(f"\nMarkdown report saved to it: {args.output}")

if __name__ == "__main__":
    main()
